#! /usr/bin/env python3

from pathlib import Path
from random import choice


with open(Path(__file__).parent / 'ships.ascii') as ships_file:
    print(choice([ship for ship in [ship.strip('\n') for ship in ships_file.read().split('\n\n')] if ship]))